In [1]:
import numpy as np

In [14]:
nd_array_0 = np.array([[1,2],[3,4],[5,6]])
transposed_array = np.array([[1,3,5],[2,4,6]])
print(nd_array_0)
print(transposed_array)
print(np.transpose(nd_array_0))
print(np.transpose(nd_array_0, axes=[1, 0]))
print(np.transpose(nd_array_0, axes=[0, 1]))

print(nd_array_0.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [26]:
np_array_d1 = np.arange(1, 9)
# print(np_array_d1)
# print(np.flip(np_array_d1))

np_array_d2 = np.arange(1, 13).reshape(3,4)
print(np_array_d2)

print(np.flip(np_array_d2, axis=0))
print(np.flip(np_array_d2, axis=1))

# print(np.flip(np.flip(np_array_d2, axis=0), axis=1))
print(np.flip(np_array_d2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [36]:
print(np_array_d2)
print(np_array_d2.flatten())
print(np_array_d2.flatten(order="F"))
raveled_arr = np.ravel(np_array_d2, order="F")

print(raveled_arr)
print(np_array_d2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  5  9  2  6 10  3  7 11  4  8 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[100   5   9   2   6  10   3   7  11   4   8  12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
# print(np_array_d2)
# np.save("np_array_d2", np_array_d2)
# np.savez("np_arrays", np_array_d2, np_array_d1)
# np.savetxt("np_array_to_file.txt", np_array_d2)

In [53]:
load_np_array = np.load("np_arrays.npz")['arr_1']
print(load_np_array)

txt_arr = np.loadtxt("np_array_to_file.txt")
print(txt_arr)

[1 2 3 4 5 6 7 8]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
