In [11]:
import numpy as np

In [12]:
sd_list = [
            [0, 0, 0],
            [1, 1, 1]
           ]

td_list = [[[0, 100, 0],[100, 1, 1]],[[10, 100, 10.1],[110, 11, 11]],[[20, 20, 20],[21, 21, 21]]]

fd_nd_array = np.array([0, 0, 0])
sd_nd_array = np.array(sd_list)
td_nd_array = np.array(td_list)

print(fd_nd_array)
print("\n")
print(sd_nd_array)
print("\n")
print(td_nd_array)
print(np.sort(td_nd_array))

[0 0 0]


[[0 0 0]
 [1 1 1]]


[[[  0.  100.    0. ]
  [100.    1.    1. ]]

 [[ 10.  100.   10.1]
  [110.   11.   11. ]]

 [[ 20.   20.   20. ]
  [ 21.   21.   21. ]]]
[[[  0.    0.  100. ]
  [  1.    1.  100. ]]

 [[ 10.   10.1 100. ]
  [ 11.   11.  110. ]]

 [[ 20.   20.   20. ]
  [ 21.   21.   21. ]]]


In [13]:
zero_td_array = np.zeros((3,2,3))
print(zero_td_array)

zero_td_array = np.ones((3,2,3))
print(zero_td_array)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [14]:
empty_array = np.empty((2,3))
print(empty_array)

[[0.e+000 0.e+000 0.e+000]
 [5.e-324 5.e-324 5.e-324]]


In [15]:
# print(list(range(10)))
# print(list(range(10,0,-1)))
# print(list(range(2,10)))

print(np.arange(10))
print(np.arange(2,10))
print(np.arange(10,0,-0.5))

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5  1.   0.5]


In [16]:
print(np.linspace(10, 20, num=3))

[10. 15. 20.]


In [17]:
original_num_list = [[2,1,5],[3,20,1],[5,8,9]]

before_sorted_array = np.array(original_num_list)

# print(original_num_list)
# print(sorted(original_num_list))

# original_num_list.sort()
# print(original_num_list)

print(before_sorted_array)
print()
before_sorted_array = np.sort(before_sorted_array, axis=0)
before_sorted_array = np.sort(before_sorted_array, axis=1)
# print(np.sort(before_sorted_array))
print(before_sorted_array)



[[ 2  1  5]
 [ 3 20  1]
 [ 5  8  9]]

[[ 1  1  2]
 [ 3  5  8]
 [ 5  9 20]]


In [18]:
list_1 = [2,1,5]
list_2 = [3,20,1]

np_array_1 = np.array(list_1)
np_array_2 = np.array(list_2)

np_array_3 = np.array([[1,2],[3,4]])
np_array_4 = np.array([[4,6,10,20], [1,2,3,4]])

# print(list_1 + list_2)
# print(np_array_1 + np_array_2)
# print(np.concatenate((np_array_1, np_array_2)))
print(np_array_3)
print()
print(np_array_4)
print()
print(np.concatenate((np_array_3, np_array_4), axis=1))


[[1 2]
 [3 4]]

[[ 4  6 10 20]
 [ 1  2  3  4]]

[[ 1  2  4  6 10 20]
 [ 3  4  1  2  3  4]]


In [19]:
before_delete_array = np.array([[4,6,10,20], [1,2,3,4], [5,6,7,8]])
print(before_delete_array)
print()
print(np.delete(before_delete_array, [0, 2], None))
print()
print(before_delete_array.ndim)
print(before_delete_array.size)
print(before_delete_array.shape)

[[ 4  6 10 20]
 [ 1  2  3  4]
 [ 5  6  7  8]]

[ 6 20  1  2  3  4  5  6  7  8]

2
12
(3, 4)


In [20]:
new_array = np.arange(8)
print(new_array)
print()
print(new_array.reshape(2, 4))
print()
print(np.reshape(new_array, (2, 4)))
print()
print(new_array)

[0 1 2 3 4 5 6 7]

[[0 1 2 3]
 [4 5 6 7]]

[[0 1 2 3]
 [4 5 6 7]]

[0 1 2 3 4 5 6 7]


In [22]:
# test_list = [1,2,4,5,6,20,7,3]
# print(test_list[6])
# print(test_list[2:5])
# print(test_list[2:])
# print(test_list[:5])
# print(test_list[:])

test_list_2d = [[1,2,4,5],[6,20,7,3]]
# print(test_list_2d)
# print(test_list_2d[1][2])
# print()
nd_array_2d = np.array(test_list_2d)
# print(nd_array_2d)
# print(nd_array_2d[1][2])
# print(nd_array_2d[1, 2])
# print(nd_array_2d[1, -1])
# print(nd_array_2d[1])

big_array_2d = np.arange(40).reshape(5,8)
print(big_array_2d)
# print(big_array_2d[3, 4])
# print(big_array_2d[:, 4:])

filtered_a = (big_array_2d % 5 == 0) & (big_array_2d >= 10)

print(big_array_2d[filtered_a])

# fancy indexing

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]
[10 15 20 25 30 35]


In [27]:
fancy_indexed_1 = big_array_2d > 10
fancy_indexed_2 = big_array_2d % 2 == 1

print(big_array_2d[fancy_indexed_1])
print(big_array_2d[fancy_indexed_2].reshape(5,4))


[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]]
