In [35]:
import numpy as np

ndarray_1d = np.array([1,2,3,4,5,6,7,8])

# print(ndarray_1d.reshape(1,8).shape)

# print(ndarray_1d)
# print(ndarray_1d.ndim)
# print(ndarray_1d.size)
# print(ndarray_1d.shape)

ndarray_2d = ndarray_1d[np.newaxis, :]
ndarray_2d = ndarray_1d[:, np.newaxis]

print(ndarray_2d)
print(ndarray_2d + ndarray_1d)

# print(ndarray_2d)
# print(ndarray_2d.ndim)
# print(ndarray_2d.size)
# print(ndarray_2d.shape)

ndarray_2d_sample = np.array([[1,2,3],[4,5,6]])
print()

# print(ndarray_2d_sample.ndim)
# print(ndarray_2d_sample.size)
# print(ndarray_2d_sample.shape)

ndarray_3d = ndarray_2d_sample[:, np.newaxis, :] * ndarray_2d_sample
# print(ndarray_2d_sample[:, np.newaxis, :])
# print(ndarray_3d)
# print()

# print(ndarray_3d.ndim)
# print(ndarray_3d.size)
# print(ndarray_3d.shape)

# print(ndarray_3d[:, :, :, np.newaxis])

# expanded_ndarray = np.expand_dims(ndarray_2d_sample, axis=(0,-1))
# print(expanded_ndarray.ndim)
# print(expanded_ndarray.size)
# print(expanded_ndarray.shape)

# print(np.expand_dims(ndarray_2d_sample, axis=(0,3,4)))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]
 [ 8  9 10 11 12 13 14 15]
 [ 9 10 11 12 13 14 15 16]]



In [62]:
array_2d = np.arange(36).reshape(6,6)
# print(array_2d)
# print()

array_1, array_2, array_3 = np.vsplit(array_2d, 3)

# for splitted_array in np.vsplit(array_2d, 3):
#   print(splitted_array)

# for splitted_array in np.vsplit(array_2d, (0, 2, 3, 5)):
#   print(splitted_array)

# for sp_ar in np.hsplit(array_2d, (1,5)):
#   print(sp_ar)

splitted_array1 = np.array([[1,2],[3,4]])
splitted_array2 = np.array([[10,20],[30,40]])

print(splitted_array1)
print(splitted_array2)
print()
print(np.vstack((splitted_array2, splitted_array1)))
# print(np.hstack((splitted_array2, splitted_array1)))

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]

[[10 20]
 [30 40]
 [ 1  2]
 [ 3  4]]


In [75]:
splitted_array2 = np.array([[10,20],[30,40]])

# copied_array = splitted_array2
copied_array = splitted_array2.copy()

print(copied_array)
print(splitted_array2)

splitted_array2[0] = 0
# print(copied_array is splitted_array2)

print(copied_array)
print(splitted_array2)

print(id(copied_array))
print(id(splitted_array2))

[[10 20]
 [30 40]]
[[10 20]
 [30 40]]
[[10 20]
 [30 40]]
[[ 0  0]
 [30 40]]
140489186978352
140489186653488


In [87]:
import copy

test_a = 10
test_b = test_a

print(test_a)
# print(test_b)
print(id(test_a))

test_a += 1

print(test_a)
# print(test_b)
# print(test_a is test_b)
print(id(test_a))
# print(id(test_b))

list_a = [1,2,3]
list_b = list_a.copy()

print(list_a)
print(id(list_a))

list_a[1] = 20

print(list_a)
print(list_b)
print(id(list_a))
print(id(list_b))

user_info = [{"name":"sam", "nickname":"sam110"}, {"name":"amy", "nickname":"am001"}]
copied_user_info = copy.deepcopy(user_info)

print(user_info)
print(copied_user_info)

user_info[1]["nickname"] = "changednickname"

print(user_info)
print(copied_user_info)

10
94250058804000
11
94250058804032
[1, 2, 3]
140489185658672
[1, 20, 3]
[1, 2, 3]
140489185658672
140489185658832
[{'name': 'sam', 'nickname': 'sam110'}, {'name': 'amy', 'nickname': 'am001'}]
[{'name': 'sam', 'nickname': 'sam110'}, {'name': 'amy', 'nickname': 'am001'}]
[{'name': 'sam', 'nickname': 'sam110'}, {'name': 'amy', 'nickname': 'changednickname'}]
[{'name': 'sam', 'nickname': 'sam110'}, {'name': 'amy', 'nickname': 'am001'}]


In [92]:
print(3 + 10)
print("abc" + "100")
print([1,2,3] + [10,11,12])
print(np.array([1,2,3]) * np.array([10,11,12]))

13
abc100
[1, 2, 3, 10, 11, 12]
[10 22 36]


In [106]:
array_0 = np.array([1,2,3,4])
array_0_2d = np.array([[10,2,30],[4,5,6]])

print(array_0.sum())
print(array_0_2d.sum())
print(array_0_2d.sum(axis=1))

print(array_0.max())
print(array_0_2d.max())
print(array_0_2d.max(axis=0))

print(array_0.min())
print(array_0_2d.min())
print(array_0_2d.min(axis=0))

print(array_0.mean())
print(array_0_2d.mean())
print(array_0_2d.mean(axis=0))

print(array_0.std())
print(array_0_2d.std())
print(array_0_2d.std(axis=0))

print(array_0.var())
print(array_0_2d.var())
print(array_0_2d.var(axis=0))

array_1_2d = np.array([[1,0], [0,1]])
array_2_2d = np.array([[2,2], [2,2]])

print(array_1_2d.dot(array_2_2d))#.dot(~~~~~))

print(np.matmul(array_1_2d, array_2_2d))

10
57
[42 15]
4
30
[10  5 30]
1
2
[4 2 6]
2.5
9.5
[ 7.   3.5 18. ]
1.118033988749895
9.482439911049617
[ 3.   1.5 12. ]
1.25
89.91666666666667
[  9.     2.25 144.  ]
[[2 2]
 [2 2]]
[[2 2]
 [2 2]]


In [113]:
array_1_2d = np.array([[5,4], [0,1]])

print(array_1_2d)
print(array_1_2d * 10.7)

test_sample_arr_0 = np.array([[1,2,3,4]])
test_sample_arr_1 = np.array([[10,20,30,40],[1,2,3,4]])

print(test_sample_arr_0.shape)
print(test_sample_arr_1.shape)
print(test_sample_arr_0 * test_sample_arr_1)
# print(array_1_2d * 10.7)

[[5 4]
 [0 1]]
[[53.5 42.8]
 [ 0.  10.7]]
(1, 4)
(2, 4)
[[ 10  40  90 160]
 [  1   4   9  16]]


In [136]:
print(np.random.randint(5, 10, size=(2,5)))

[7 6 5 6 6 9 8 8 7 8]


In [141]:
print(np.random.rand(2,5))

[[0.30599003 0.37530972 0.24221649 0.11060205 0.43501827]
 [0.55222925 0.91493244 0.45603548 0.22447258 0.02437755]]


In [143]:
print(np.random.randn(2, 5))

[[-0.04346496 -1.84685662  1.4340525   0.70358146  0.24664844]
 [-0.63663505 -0.27965133  0.29765944  1.25180706 -0.84715659]]


In [145]:
test_a = np.arange(10)
print(test_a)
print(np.random.shuffle(test_a))
print(test_a)

test_a = np.arange(9).reshape(3, 3)
print(test_a)
print(np.random.shuffle(test_a))
print(test_a)

[0 1 2 3 4 5 6 7 8 9]
None
[3 9 2 6 1 4 8 7 5 0]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
None
[[6 7 8]
 [0 1 2]
 [3 4 5]]


In [157]:
simulated_result = np.random.choice(["red", "yellow", "blue"], 10000, p=[0.3, 0.2, 0.5])

r_array = (simulated_result == "red")
y_array = (simulated_result == "yellow")
b_array = (simulated_result == "blue")

print(f"red: {r_array.sum()}")
print(f"yellow: {y_array.sum()}")
print(f"blue: {b_array.sum()}")

red: 2935
yellow: 1985
blue: 5080


In [171]:
duplicated_array = np.random.randint(10, 15, 10)
print(duplicated_array)

print(np.unique(duplicated_array, return_counts=True, return_inverse=True))

[10 13 14 14 12 13 13 12 14 14]
(array([10, 12, 13, 14]), array([0, 2, 3, 3, 1, 2, 2, 1, 3, 3]), array([1, 2, 3, 4]))
